{
  "Graph": {
    "Kind": "Action",
    "Variables": [
      {
        "Id": 5,
        "Name": "_this",
        "Type": "Sandbox.Game/Sandbox.Component",
        "Input": "_this"
      }
    ],
    "Nodes": [
      {
        "Id": 0,
        "Type": "input",
        "Properties": {
          "parameters": [
            {
              "Name": "_in1",
              "Type": "Sandbox.Game/Sandbox.GameObject",
              "IsRequired": true,
              "Display": {
                "Title": "Input 1"
              }
            },
            {
              "Name": "_this",
              "Type": "Sandbox.Game/Sandbox.Component",
              "IsRequired": true
            }
          ]
        },
        "UserData": {
          "Position": "-756,0"
        }
      },
      {
        "Id": 1,
        "Type": "foreach",
        "UserData": {
          "Position": "-24,-128"
        }
      },
      {
        "Id": 2,
        "Type": "property.get",
        "Properties": {
          "_type": "package.local.retrofps/ButtonComponent",
          "_name": "ToTrigger"
        },
        "UserData": {
          "Position": "-280,-64"
        }
      },
      {
        "Id": 3,
        "Type": "graph",
        "Properties": {
          "graph": "actions/use.action"
        },
        "UserData": {
          "Position": "456,64"
        }
      },
      {
        "Id": 4,
        "Type": "call",
        "Properties": {
          "_type": "Sandbox.Game/Sandbox.IComponentLister",
          "_name": "Get",
          "_isStatic": false,
          "T": {
            "$type": "Type",
            "Type": "package.local.retrofps/ButtonComponent"
          }
        },
        "UserData": {
          "Position": "-456,128"
        }
      }
    ],
    "Links": [
      [
        1,
        "body",
        3,
        "_signal"
      ],
      [
        1,
        "body.value",
        3,
        "_in1"
      ],
      [
        2,
        "_result",
        1,
        "enumerable"
      ],
      [
        4,
        "_result",
        2,
        "target"
      ],
      [
        0,
        "_signal",
        1,
        "_signal"
      ],
      [
        0,
        "_in1",
        4,
        "_target"
      ]
    ],
    "UserData": {
      "Title": "Buttonuse",
      "Description": "No description provided.",
      "Icon": "account_tree",
      "Category": "Custom"
    }
  },
  "__references": []
}